remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
description: En esta sección se encuentran las instrucciones detalladas de cada una de las máquinas vulnerables desplegadas. Cada máquina representa un entorno aislado con una temática específica, basada en los siete pecados capitales.